services:
  db-postgres:
    image: postgres:15

    container_name: eco_assistant_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=ecoassistant
    ports:
      - "5433:5432" #Mapping host  5433 to container  5432, bch nkhalli l 5432 l local
    volumes:
      - db-data:/var/lib/postgresql/data
  
volumes:
  db-data:
